source $TACHIKOMA/textstyles.sh

if [ $USER = "root" ]; then
    USER_COLOR=$FG_RED
    TIME_COLOR=$FG_RED
    CMD_COLOR=$FG_RED
else
    USER_COLOR=$FG_BLUE
    TIME_COLOR=$FG_PURPLE
    CMD_COLOR=$FG_GREEN
fi

PS_USER="$TEXT_BOLD$USER_COLOR\u@\h$TEXT_RESET"
PS_TIME="$TEXT_BOLD$TIME_COLOR\t$TEXT_RESET"
PS_CWD="\w"
PS_CMD="$TEXT_BOLD$CMD_COLOR>$TEXT_RESET"

export PS1="\n${PS_USER} ${PS_TIME} ${PS_CWD}\n${PS_CMD} "
